### ISSUE TITLE
Explore page - Re-label Submitted by and Submittted From Quick Searches

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#10]
Replace **Submitted By** and **Submitted From** with 
'Contributed By...' and 'From Post Code ...'

More generally, we should be more consistent in our terminology, referring to traceroute Contributors and Contributions, rather than submissions.

**Comment by colinmccann** [comment]
Updated with those labels. Found one other place that specifically references the button (in the Help section) - plz keep an eye out for further references to 'Submitted By' or 'Submitted From' buttons

**Comment by Andrew-Clement** [comment]
Good to see this quick correction, but there are other place where Submitter should be changed to Contributor  eg see the 3  just above, plus Submitter Postcode in pull down menu ('Post Code' or Postcode' We should be consistent.  I suggest the latter as slightly more concise.
![pastedgraphic-17](https://cloud.githubusercontent.com/assets/12848029/16534876/e4c17f3e-3f97-11e6-9a97-61482c22d7df.png)

**Comment by colinmccann** [comment]
This is a much bigger fix than I had assumed, but I can go ahead and do
that.

We will still be using 'submitter' internally, which will add to the
confusion

On Fri, Jul 1, 2016 at 5:29 PM, Andrew-Clement <notifications@github.com>
wrote:

> Good to see this quick correction, but there are other place where
> Submitter should be changed to Contributor eg see the 3 just above, plus
> Submitter Postcode in pull down menu ('Post Code' or Postcode' We should be
> consistent. I suggest the latter as slightly more concise.
> [image: pastedgraphic-17]
> <https://cloud.githubusercontent.com/assets/12848029/16534876/e4c17f3e-3f97-11e6-9a97-61482c22d7df.png>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ixmaps/website/issues/10#issuecomment-230051398>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuEmN8u82kL5KiA8Py9aj5IDegH1IWDks5qRYbJgaJpZM4JDant>
> .
>



-- 
Colin

**Comment by colinmccann** [comment]
(feel free to re-open issues when they are not completed to satisfaction)


-- 
Colin

**Comment by colinmccann** [comment]
After working through the implications of this, I suggest we stick with Submitter instead of Contributor (everywhere). This change was prompted by the change of the language on one button and would require many changes elsewhere (and a disconnect btw internal and external work choice, which *will* cause us confusion in the future). I believe the original issue is more easily resolved by just changing the language of the button to 'From Postcode' (and leaving the other as 'Submitted By')... they are now sufficiently distinguished imo

**Comment by Andrew-Clement** [comment]
This what I feared.  I suggest reverting the change you just made and keep this in mind what we undertake the larger makeover.

On 2016-07-01, at 2:46 PM, colinmccann <notifications@github.com> wrote:

This is a much bigger fix than I had assumed, but I can go ahead and do
that.

We will still be using 'submitter' internally, which will add to the
confusion

On Fri, Jul 1, 2016 at 5:29 PM, Andrew-Clement <notifications@github.com>
wrote:

> Good to see this quick correction, but there are other place where
> Submitter should be changed to Contributor eg see the 3 just above, plus
> Submitter Postcode in pull down menu ('Post Code' or Postcode' We should be
> consistent. I suggest the latter as slightly more concise.
> [image: pastedgraphic-17]
> <https://cloud.githubusercontent.com/assets/12848029/16534876/e4c17f3e-3f97-11e6-9a97-61482c22d7df.png>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ixmaps/website/issues/10#issuecomment-230051398>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuEmN8u82kL5KiA8Py9aj5IDegH1IWDks5qRYbJgaJpZM4JDant>
> .
>



--
Colin

**Comment by colinmccann** [comment]
I have reverted to Submitter, and have changed to postcode. This issue can
stay closed.

Andrew, I have updated the ixmaps github settings - you should have full
rights now (eg to reopen issues and to tag)

On Sat, Jul 2, 2016 at 10:45 PM, Andrew-Clement <notifications@github.com>
wrote:

> This what I feared. I suggest reverting the change you just made and keep
> this in mind what we undertake the larger makeover.
>
> On 2016-07-01, at 2:46 PM, colinmccann <notifications@github.com> wrote:
>
> This is a much bigger fix than I had assumed, but I can go ahead and do
> that.
>
> We will still be using 'submitter' internally, which will add to the
> confusion
>
> On Fri, Jul 1, 2016 at 5:29 PM, Andrew-Clement <notifications@github.com>
> wrote:
>
> > Good to see this quick correction, but there are other place where
> > Submitter should be changed to Contributor eg see the 3 just above, plus
> > Submitter Postcode in pull down menu ('Post Code' or Postcode' We should
> be
> > consistent. I suggest the latter as slightly more concise.
> > [image: pastedgraphic-17]
> > <
> https://cloud.githubusercontent.com/assets/12848029/16534876/e4c17f3e-3f97-11e6-9a97-61482c22d7df.png
> >
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/ixmaps/website/issues/10#issuecomment-230051398>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AAuEmN8u82kL5KiA8Py9aj5IDegH1IWDks5qRYbJgaJpZM4JDant
> >
> > .
> >
>
>
>
> --
> Colin
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ixmaps/website/issues/10#issuecomment-230132145>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuEmPlv3vSxRKGs-sU9vvb-boINy2WWks5qRyJVgaJpZM4JDant>
> .
>



-- 
Colin

**Comment by Andrew-Clement** [comment]
Thanks.

On 2016-07-04, at 3:59 PM, colinmccann <notifications@github.com> wrote:

I have reverted to Submitter, and have changed to postcode. This issue can
stay closed.

Andrew, I have updated the ixmaps github settings - you should have full
rights now (eg to reopen issues and to tag)

On Sat, Jul 2, 2016 at 10:45 PM, Andrew-Clement <notifications@github.com>
wrote:

> This what I feared. I suggest reverting the change you just made and keep
> this in mind what we undertake the larger makeover.
>
> On 2016-07-01, at 2:46 PM, colinmccann <notifications@github.com> wrote:
>
> This is a much bigger fix than I had assumed, but I can go ahead and do
> that.
>
> We will still be using 'submitter' internally, which will add to the
> confusion
>
> On Fri, Jul 1, 2016 at 5:29 PM, Andrew-Clement <notifications@github.com>
> wrote:
>
> > Good to see this quick correction, but there are other place where
> > Submitter should be changed to Contributor eg see the 3 just above, plus
> > Submitter Postcode in pull down menu ('Post Code' or Postcode' We should
> be
> > consistent. I suggest the latter as slightly more concise.
> > [image: pastedgraphic-17]
> > <
> https://cloud.githubusercontent.com/assets/12848029/16534876/e4c17f3e-3f97-11e6-9a97-61482c22d7df.png
> >
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/ixmaps/website/issues/10#issuecomment-230051398>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AAuEmN8u82kL5KiA8Py9aj5IDegH1IWDks5qRYbJgaJpZM4JDant
> >
> > .
> >
>
>
>
> --
> Colin
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ixmaps/website/issues/10#issuecomment-230132145>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuEmPlv3vSxRKGs-sU9vvb-boINy2WWks5qRyJVgaJpZM4JDant>
> .
>



--
Colin
