### ISSUE TITLE
explore page - alert first time visitors that the route shown is the latest contributed. 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#14]
From my (limited) testing, novices are unclear about what they are seeing when they are directed to the explore page. 

I suggest a brief, fading pop-up that reads:
"The map shows the path of the most recent traceroute contributed to the IXmaps database. For more details, see panels on the right,  hover over the routers (dots) and click on the hops (lines)" (or some such) 

Proposed Labels: (Until I can figure out how to label issues myself, please label this item as:
Issue Type: bug duplicate **enhancement** help wanted out of scope question wontfix
Importance: critical **major** minor
Urgency: immediate **soon** whenever
Difficulty: wicked hard **easy** (this is my perception of difficulty, please correct if I'm mistaken)
See also issue #15

**Comment by dcwalk** [comment]
Might make sense to have the difficulty assessments added by @colinmccann or @agamba based on implementation considerations?
Also -- more generally I think that some of these identified enhancements might be held until a redesign is finalized, which would impact the importance/urgency

**Comment by colinmccann** [comment]
I read the assigned difficulties as a range from easy to 'wicked hard'.
Surfs up dude!

On Sun, Jul 3, 2016 at 5:08 PM, dcwalk <notifications@github.com> wrote:

> Might make sense to have the difficulty assessments added by @colinmccann
> <https://github.com/colinmccann> or @agamba <https://github.com/agamba>
> based on implementation considerations?
> Also -- more generally I think that some of these identified enhancements
> might be held until a redesign is finalized, which would impact the
> importance/urgency
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ixmaps/website/issues/14#issuecomment-230175446>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuEmDEfScifr-PtA6t5IvT-FJoJdjBrks5qSCS2gaJpZM4JDvj5>
> .
>



-- 
Colin

**Comment by Andrew-Clement** [comment]
Well, I had in mind wicked being different from hard, ie REAL hard, requiring a lot of thought and skill - a great big roller that will be very challenging to ride out but (hopefully) will take you far-rrr.

**Comment by colinmccann** [comment]
Heh, yeah.

This was indeed, easy - closing...

On Mon, Jul 4, 2016 at 7:08 PM, Andrew-Clement <notifications@github.com>
wrote:

> Well, I had in mind wicked being different from hard, ie REAL hard,
> requiring a lot of thought and skill - a great big roller that will be very
> challenging to ride out but (hopefully) will take you far-rrr.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ixmaps/website/issues/14#issuecomment-230362393>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuEmAQbfdM8CAnss33LKIy3ew9zY3tFks5qSZKEgaJpZM4JDvj5>
> .
>



-- 
Colin
