### ISSUE TITLE
github labeling 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#15]
As mentioned, I appear not to be able to attach labels or create new ones, perhaps because I lack permission, or am missing something (due to approaching senility??)

I would appreciate being coached into this.

In the meantime, someone please add the following 9 labels to the existing ones: 

critical major minor  (related to Importance: ie the contribution it would make to project overall)
immediate soon whenever (related to Urgency: how quickly it needs doing
wicked hard easy (related to Difficulty: the time and resources needed to address the issue)

I propose colour coding each in  the conventional red/yellow/green fashion, with red assigned to critical immediate and wicked (though perhaps the difficulty spectrum needs a different colour scheme??)

I'd welcome feedback on the appropriateness and usefulness of this labeling scheme.

Please label this item as:
Issue Type: bug duplicate enhancement **help wanted** out of scope question wontfix
Importance: critical **major** minor
Urgency: **immediate** soon whenever
Difficulty: wicked hard **easy**

**Comment by agamba** [comment]
You should see the words "labels" on the right side of the title of an issue. 

<img width="1022" alt="screen shot 2016-07-02 at 8 25 26 pm" src="https://cloud.githubusercontent.com/assets/999407/16543113/fd67bcc2-4093-11e6-8aee-922ee2ecdf6c.png">

Creating labels, got the the main issues page
https://github.com/ixmaps/website/issues
click on "Labels", then "New label"

<img width="1014" alt="screen shot 2016-07-02 at 8 28 58 pm" src="https://cloud.githubusercontent.com/assets/999407/16543119/3351e3b2-4094-11e6-8c27-71811a2075ef.png">

<img width="1035" alt="screen shot 2016-07-02 at 8 29 07 pm" src="https://cloud.githubusercontent.com/assets/999407/16543121/382abf9e-4094-11e6-8484-b35842159c1a.png">

**Comment by Andrew-Clement** [comment]
Thanks Antonio,

While I see  Labels where you describe:

 it doesn't respond to being clicked, so it is not an active link for me.

Ditto here:


Is there some permission setting that would make it active?


BTW, how do you draw the the red lines for highlighting??



On 2016-07-02, at 5:33 PM, Antonio Gamba-Bari <notifications@github.com> wrote:

You should see the words "labels" on the right side of the title of an issue.



Creating labels, got the the main issues page
https://github.com/ixmaps/website/issues
click on "Labels", then "New label"

**Comment by dcwalk** [comment]
Hiya @Andrew-Clement... you should be able to add labels now.
I created the difficulty and important sets, but suggest that the **urgency** be folded into _importance_. Conceptually they are quick similar and I think there would only be a few edge cases where something was of critical important but not an immediate fix.

**Comment by Andrew-Clement** [comment]
Thanks Dawn,

However, I'm still not able to label, or assign, … I was already a member.

I see at https://github.com/orgs/ixmaps/people that I'm just a member and the rest of you are owners, so  so I suspect this is an authorization setting that prevents me from these actions
.
I
Could you try changing my status to owner.

Thanks.

Andrew.




On 2016-07-03, at 2:02 PM, dcwalk <notifications@github.com> wrote:

Hiya @Andrew-Clement... you should be able to add labels now.
I created the difficulty and important sets, but suggest that the urgency be folded into importance. Conceptually they are quick similar and I think there would only be a few edge cases where something was of critical important but not an immediate fix.

**Comment by agamba** [comment]
Assign a label to an issue, click on the "gear" icon, not sure about your privileges?
<img width="65" alt="screen shot 2016-07-03 at 10 00 58 pm" src="https://cloud.githubusercontent.com/assets/999407/16549161/dd3636d2-4169-11e6-91c5-f3ebf8de5cf7.png">

<img width="379" alt="screen shot 2016-07-03 at 9 57 49 pm" src="https://cloud.githubusercontent.com/assets/999407/16549168/ea652232-4169-11e6-8fea-47f4b5368112.png">

**Comment by dcwalk** [comment]
This should be resolved! Can you reopen if you are still experiencing problems?

**Comment by Andrew-Clement** [comment]
Thanks whomever, Dawn?, for inviting me as an owner with admin privileges. Seems to be working now.

On 2016-07-04, at 12:10 PM, dcwalk <notifications@github.com> wrote:

This should be resolved! Can you reopen if you are still experiencing problems?
