### ISSUE TITLE
Can site response times be improved??

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#21]
Since we are moving to the new server, it's not worth spending much time on this, but if there is an easy way to tune up the performance of the iSchool site, it would help with the testing (eg free up space?).  It adds to the friction for visitors, discouraging them from continuing, and those who persist will be more likely to comment on response time than other things that aren't so obvious to us. (Already with a small number of respondents (OM staff), several have commented on this).

**Comment by colinmccann** [comment]
This is not something that can fixed at this point, to my knowledge.
There's plenty of disk space, eg. RAM is likely more the issue, as well as
the size of our DB and query quality. We can only look to fix this on the
next server, I'd imagine - Anto might have ideas tho

On Fri, Jul 8, 2016 at 3:45 PM, Andrew-Clement <notifications@github.com>
wrote:

> Assigned #21 <https://github.com/ixmaps/website/issues/21> to @colinmccann
> <https://github.com/colinmccann>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ixmaps/website/issues/21#event-717442133>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuEmPsAqoJVacRVm-xB5cr0RZH6hVDaks5qTqj0gaJpZM4JIVug>
> .
>



-- 
Colin

**Comment by agamba** [comment]
I don't think there is a quick fix for this. Memory looks a bit low. Also the issue I think is associated to the whole stack apache/php/postgres. They are all old versions, but it might be risky to attempt an  update at this moment. I could request more cpu and ram.

Cpu(s):  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3108480k total,  2432132k used,   676348k free,   165028k buffers
Swap:  1510068k total,      620k used,  1509448k free,  1913128k cached

**Comment by Andrew-Clement** [comment]
Thanks.

 I agree that updating at this point is too risky, but a request for more cpu and ram wouldn't hurt.  I'd be glad to make the request, but not sure who to ask, and likely wouldn't happen until Monday at best.  Glenn I suppose, but then he'd pass it on to someone else. Suggestions?




On 2016-07-08, at 2:15 PM, Antonio Gamba-Bari <notifications@github.com> wrote:

I don't think there is a quick fix for this. Memory looks a bit low. Also the issue I think is associated to the whole stack apache/php/postgres. They are all old versions, but it might be risky to attempt an update at this moment. I could request more cpu and ram.

Cpu(s): 0.0%us, 0.0%sy, 0.0%ni,100.0%id, 0.0%wa, 0.0%hi, 0.0%si, 0.0%st
Mem: 3108480k total, 2432132k used, 676348k free, 165028k buffers
Swap: 1510068k total, 620k used, 1509448k free, 1913128k cached

**Comment by dcwalk** [comment]
I am closing this as wont fix based on discussion about moving to the new server.
