### ISSUE TITLE
Explore/TRdetails discrepancies between Standard and Technical versions 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#32]
The Standard and Technical versions of TRdetails sometimes don't correspond directly to each other, usually the Tech version has an additional hop. eg compare the versoins for TR 336200

Standard version
Traceroute details: ID 336200 created on 2017-02-05 19:57:47.820039-05 	
Origin: Submitted by AndrewC from V8K2W9
Destination: www.ppcatalunya.com [104.31.166.4]

Hop 	IP Address 		Min. Latency 	Carrier 	Geolocation 	Geoprecision 	Hostname 	Flag
1 	70.67.160.0 		9 	Shaw 	Chemainus BC 	Maxmind 	70.67.160.0 	Flag This IP
2 	64.59.162.213 		13 	Shaw 		Maxmind 	rd2bb-tge0-4-0-11-1.no.shawcable.net 	Flag This IP
3 	66.163.72.10 		15 	Shaw 	Victoria BC 	city level 	ra1cv-ge1-1.gv.shawcable.net 	Flag This IP
4 	66.163.68.18 		15 	Shaw 	Seattle WA 	city level 	rc4wt-ge2-0-0.wa.shawcable.net 	Flag This IP
5 	206.81.81.10 		15 	-Reserved AS- 	Seattle WA 	Maxmind 	six.as13335.com 	Flag This IP

Technical version
Traceroute details: ID 336200 created on 2017-02-05 19:57:47.820039-05 	
Origin: Submitted by AndrewC from V8K2W9
Destination: www.ppcatalunya.com [104.31.166.4]

Hop 	IP Address 	Round Trip Times 	AS# 	Latitude 	Longitude 	Hostname 	Flag
1 	70.67.160.0 	9 	10 	10 	10 	6327 	48.9203 	-123.7187 	70.67.160.0 	Flag This IP
2 	64.59.162.213 	13 	14 	16 	17 	6327 	43.6319 	-79.3716 	rd2bb-tge0-4-0-11-1.no.shawcable.net 	Flag This IP
3 	66.163.72.10 	15 	15 	16 	19 	6327 	48.42 	-123.37 	ra1cv-ge1-1.gv.shawcable.net 	Flag This IP
4 	66.163.68.18 	15 	15 	16 	17 	6327 	47.61 	-122.33 	rc4wt-ge2-0-0.wa.shawcable.net 	Flag This IP
5 	206.81.81.10 	15 	15 	15 	16 	-1 	47.7396 	-122.343 	six.as13335.com 	Flag This IP
6 	104.31.166.4 	15 	16 	18 	21 	13335 	37.7697 	-122.3933 	104.31.166.4 	Flag This IP

**Comment by agamba** [comment]
This needs further discussion. Here the db data for comparison

ixmaps=# select * from tr_item where traceroute_id = 336200 order by hop, attempt;
 traceroute_id | hop | attempt | status |    ip_addr    | rtt_ms 
---------------+-----+---------+--------+---------------+--------
        336200 |   1 |       1 | r      | 70.67.160.0   |      9
        336200 |   1 |       2 | r      | 70.67.160.0   |     10
        336200 |   1 |       3 | r      | 70.67.160.0   |     10
        336200 |   1 |       4 | r      | 70.67.160.0   |     10
        336200 |   2 |       1 | r      | 64.59.162.213 |     13
        336200 |   2 |       2 | r      | 64.59.162.213 |     14
        336200 |   2 |       3 | r      | 64.59.162.213 |     16
        336200 |   2 |       4 | r      | 64.59.162.213 |     17
        336200 |   3 |       1 | r      | 66.163.72.10  |     15
        336200 |   3 |       2 | r      | 66.163.72.10  |     15
        336200 |   3 |       3 | r      | 66.163.72.10  |     16
        336200 |   3 |       4 | r      | 66.163.72.10  |     19
        336200 |   4 |       1 | r      | 66.163.68.18  |     15
        336200 |   4 |       2 | r      | 66.163.68.18  |     15
        336200 |   4 |       3 | r      | 66.163.68.18  |     16
        336200 |   4 |       4 | r      | 66.163.68.18  |     17
        336200 |   5 |       1 | r      | 206.81.81.10  |     15
        336200 |   5 |       2 | r      | 206.81.81.10  |     15
        336200 |   5 |       3 | r      | 206.81.81.10  |     15
        336200 |   5 |       4 | r      | 206.81.81.10  |     16
        336200 |   6 |       1 | r      | 104.31.166.4  |     15
        336200 |   6 |       2 | r      | 104.31.166.4  |     16
        336200 |   6 |       3 | r      | 104.31.166.4  |     18
        336200 |   6 |       4 | r      | 104.31.166.4  |     21
(24 rows)

**Comment by colinmccann** [comment]
Yes, this is a long standing issue - however, I suggest we do not spend more time on outdated code unless it's essential for your presentation. Closing for now...
