### ISSUE TITLE
Explore Page new functionality brakes access to unique TRids from IXmapsClient

### ISSUE THREAD

**Issue by agamba** [ixmaps/website#34]
The recently added functionality for the Explore page, using user location to create a query, introduces as bug for the display of individual traceroutes from the IXmapsClient.

The fix will require checking if parameters are sent to the explore.php, for example:
https://www.ixmaps.ca/explore.php?trid=336556

<img width="1032" alt="screen shot 2017-02-17 at 4 40 57 pm" src="https://cloud.githubusercontent.com/assets/999407/23084467/74ea49f8-f530-11e6-9c6d-6a3e4bbd95ca.png">

<img width="953" alt="screen shot 2017-02-17 at 4 41 09 pm" src="https://cloud.githubusercontent.com/assets/999407/23084477/79ad83a6-f530-11e6-8543-129410e4f79e.png">

**Comment by colinmccann** [comment]
Good catch - fixed now? Can close?

**Comment by agamba** [comment]
Yes, it is fixed now
