### ISSUE TITLE
Geo-correction - Please take a look at routers I've recently flagged

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#40]
In my labours to find a few suitable illustrative routes for my talk on Wed in Vancouver, I    flagged a number of routes. I presume these are easy spot.  It would be helpful to me if you can geo-collect them.

**Comment by colinmccann** [comment]
@Andrew-Clement I don't think this is the place for these... geocorrection is quite unrelated to this code base. Email likely better.

However, I have complete (most of) the flagged items, comments in brackets:
  392 | 75.154.217.108  | 2017-02-20 19:42:40-05 | Seattle is fine, ISP needs correcting
  391 | 206.108.220.193 | 2017-02-20 19:34:10-05 | Vancouver
  390 | 38.88.252.161   | 2017-02-20 19:20:42-05 | Seattle
(LA, actually)
  389 | 154.24.48.218   | 2017-02-20 19:17:27-05 | Vancouver
  388 | 205.236.144.6   | 2017-02-20 19:10:53-05 | Montreal
  387 | 63.243.128.105  | 2017-02-20 16:41:19-05 | Halifax? or NYC?
(definitely NYC, hostname)
  386 | 64.86.123.150   | 2017-02-20 16:39:36-05 | Seattle? or Vancouver?
  385 | 64.59.162.0     | 2017-02-20 16:13:57-05 | This router appears as the first in another Vancouver Island initiated TR (Campbell River?), so better to put it in Victoria? 
  384 | 206.81.81.10    | 2017-02-20 14:45:43-05 | Location is fine, but needs a carrier name -SIX (Seattle IX)
(arin does not show an asn for this ip)
  383 | 206.81.81.10    | 2017-02-20 14:36:31-05 | Location is fine, but needs a carrier name (duplicate)
  382 | 97.107.178.110  | 2017-02-19 21:24:19-05 | Vancouver
(why?)
  381 | 173.205.56.222  | 2017-02-19 21:19:55-05 | Vancouver
  380 | 67.223.102.174  | 2017-02-16 22:49:25-05 | Toronto
  379 | 64.86.33.58     | 2017-02-16 22:48:50-05 | Toronto
  378 | 64.86.123.149   | 2017-02-16 22:46:40-05 | Seattle?
(Dallas)
  377 | 198.32.118.40   | 2017-02-05 19:59:31-05 | NYC
